### ISSUE TITLE
Search API - when to use keyword, order by issue

### ISSUE THREAD

**Issue by trzcina** [flotiq/flotiq-docs#158]
Search API is based on ElasticSearch, but ES knowledge should not be necessary to use standard search functions.

Search docs: https://flotiq.com/docs/API/search/

Example request with order_by, according to docs:

1. Search all [works] https://api.flotiq.com/api/v1/search?q=*&auth_token=__TOKEN__
2. Search all ordered by `created` [error]: https://api.flotiq.com/api/v1/search?q=*&order_by=created&auth_token=__TOKEN__
    
Search all ordered by causes error:
```{
        "q": [
            "Malformed query"
        ]
    }
```

We should use `created.keyword` (notice "keyword", *that is not mentioned in docs*)
https://api.flotiq.com/api/v1/search?q=*&order_by=created.keyword&auth_token=__TOKEN__
And it works fine.

Please add info on when should I use `.keyword` or refer to ES docs

**Comment by CiotkaCierpienia** [comment]
Resolved with #262
