### ISSUE TITLE
Filter description for listing content objects is wordy and hard to read

### ISSUE THREAD

**Issue by WHLukasz** [flotiq/flotiq-docs#160]
The description of filters for content object listing is chaotic and hard to read due to the sheer amount of filters and descriptions for each and every one of them. Also, examples are not clear enough, so it's harder to translate them into a project.

https://flotiq.com/docs/API/content-type/listing-co/#listing-content-through-the-api

The whole part of the page describing filters is wordy and takes up the majority of the page content. 

Please consider creating a selecting list for every filter type as you do with response examples and overall make the page more user-friendly.

**Comment by CiotkaCierpienia** [comment]
Resolved by https://github.com/flotiq/flotiq-docs/pull/234
