### ISSUE TITLE
Old copyright 2019 date on page.

### ISSUE THREAD

**Issue by MaciejLabedzkiCodewave** [flotiq/flotiq-docs#161]
Old copyright on page:

`Copyright © 2019 onwards Flotiq`

![image](https://github.com/flotiq/flotiq-docs/assets/110835434/83a95f0a-4b0e-4660-bd9c-084e9df67328)

Suggestion:
`Copyright © 2019 - [current year] Flotiq`

**Comment by CiotkaCierpienia** [comment]
The word onwards means precisely that
