### ISSUE TITLE
When we scroll to the bottom of the page will be nicer to add more height to left menu and remove full footer white width.

### ISSUE THREAD

**Issue by MaciejLabedzkiCodewave** [flotiq/flotiq-docs#164]
**Current behavior:**

![current-scroll-down](https://github.com/flotiq/flotiq-docs/assets/110835434/77fe57ed-e722-4c5e-a65d-5a76671e03be)

**Prototype fix:**

![prototype-scroll-down](https://github.com/flotiq/flotiq-docs/assets/110835434/f73ff3d5-d8e9-46dd-87df-88f759a115b3)

**Comment by CiotkaCierpienia** [comment]
The issue is referring to an older version of Flotiq Docs. On the new version left sidebar menu is behaving as expected.
