### ISSUE TITLE
Example code should have copy buttonsThere is no copy button on provided examples.

### ISSUE THREAD

**Issue by MaciejLabedzkiCodewave** [flotiq/flotiq-docs#168]
![image](https://github.com/flotiq/flotiq-docs/assets/110835434/4b4178f3-c5ef-4af1-bc42-3fed3c49387d)

Similar like in Api Docs generated from [editor.flotiq.com](https://editor.flotiq.com/)

![image](https://github.com/flotiq/flotiq-docs/assets/110835434/0a73d88d-6766-4308-9f96-e4d4e3967172)

![image](https://github.com/flotiq/flotiq-docs/assets/110835434/487ebf7a-5b98-4d66-9f82-c1fb95ddc3f2)

**Comment by WHLukasz** [comment]
fixed
