### ISSUE TITLE
Missleading CTA button below contact form

### ISSUE THREAD

**Issue by trzcina** [flotiq/flotiq-docs#169]
On the contact page there is contact form, and small button "Send".
Below is huge CTA button.

It can be misleading. 
When a user fills out a form, they may accidentally click a larger button and lose the entered data.

CTA button should be moved or "Send" button should be more visible

![image](https://github.com/flotiq/flotiq-docs/assets/645716/358b2046-402f-4c31-aca1-36fe82ac8594)

**Comment by WHLukasz** [comment]
outdated. `contact` now leads to 'https://flotiq.com/contact/'
