### ISSUE TITLE
Broken image in Flotiq Gatsby plugin docs

### ISSUE THREAD

**Issue by andrzejwp** [flotiq/flotiq-docs#175]
Missing image on [Gatsby plugin docs](https://flotiq.com/docs/panel/Plugins/Gatsby-cloud-integration/#creating-an-instance)

![image](https://github.com/flotiq/flotiq-docs/assets/3079734/b8a88d21-30cf-44f2-850c-eb2357a9ac80)

**Comment by WHLukasz** [comment]
fixed
