### ISSUE TITLE
Search API filters description vague

### ISSUE THREAD

**Issue by andrzejwp** [flotiq/flotiq-docs#49]
### Issue Summary

The description of `filters` param in the `search` API is not clear as to how the request should actually look. Additionally, the field is declared without brackets, as opposed to other fields which can take multiple values.

![image](https://user-images.githubusercontent.com/3079734/111171603-5e1d2b00-85a5-11eb-82fc-37de78c92236.png)

the documentation should be improved to clearly state how a developer can use the `filters`.

**Comment by CiotkaCierpienia** [comment]
@andrzejwp does the search documentation now:
![Flotiq-Search-API-Flotiq-docs-Flotiq-Developer-Documentation](https://user-images.githubusercontent.com/2624540/144003609-dca155df-2453-42b6-b43e-e6fc6a6e72da.png) describe `filters` better for you?

**Comment by andrzejwp** [comment]
A lot better, thanks!
