### ISSUE TITLE
Can't reach the page - Zapier

### ISSUE THREAD

**Issue by likrot** [flotiq/flotiq-docs#55]
Hi,

there is a 404 error when I click on the link [Zapier & integrations](https://flotiq.com/docs/API/zapier.md).

![error-404](https://user-images.githubusercontent.com/34319368/112444766-b0e9a600-8d4e-11eb-9e00-f462a9422d53.png)

**Comment by DominikIlski** [comment]
Hi @likrot, thank you for the report. 
We will look into that and get back with a solution as fast as possible!
