### ISSUE TITLE
API Documentation link doesn't work

### ISSUE THREAD

**Issue by likrot** [flotiq/flotiq-docs#56]
Hi,

I wanted to see the documentation you're talking about, but there is an error. Link comes from [predefined-content-types](https://flotiq.com/docs/panel/predefined-content-types/)

![link](https://user-images.githubusercontent.com/34319368/112466502-40e71a00-8d66-11eb-81a8-d86f17e5a774.png)
![error](https://user-images.githubusercontent.com/34319368/112466531-46446480-8d66-11eb-9fc0-7eaa4dbba392.png)

**Comment by DominikIlski** [comment]
Hi, @likrot thanks for the report. It's a bug and I will try to fix it as fast as possible :)
