### ISSUE TITLE
A banner rotator issue - data is not hydrated when using scoped API key

### ISSUE THREAD

**Issue by likrot** [flotiq/flotiq-docs#58]
Hi,

I've read the article about [Banner rotator](https://flotiq.com/docs/Deep-Dives/building-a-banner-rotator-with-an-admin-interface/)
It seems cool and very easy to use, but I have some problems with the example.

In your example in js code, you're using `banners` object's properties. The keys are lowercased, not such like in your example, so you should use f.eg. `{rotator.width}x${rotator.height}` instead of `{rotator.Width}x${rotator.Height}`.

I also have a problem with hydration, but only when using `fetch` in the browser. Curl and postman's responses are ok.

It doesn't work, so I cannot use additional properties like `id` or `extension`., but I've changed my scoped API key, which has all permissions to a global one and it started works.

Do you have any idea why is that?

(I'm working in local env).

### Issue Summary

Hydration does not work with scoped API key.

**Comment by likrot** [comment]
It seems that lowercase in object's property names and its incompatibility with your guide is my fault. I named it in that way automatically (lowercase I mean).

**Comment by CiotkaCierpienia** [comment]
Looks like code, not documentation problem, closing.
